default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>

development:
  <<: *default
  database: words_api_development

test:
  <<: *default
  database: words_api_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
url: <%= ENV.fetch('DATABASE_URL') %>
